"""empty message

Revision ID: 177f6cc9c883
Revises: 7f005a30fe3e
Create Date: 2022-05-21 02:27:18.438673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f6cc9c883'
down_revision = '7f005a30fe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.Column('datevote', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
